version: '3.3'
services:
  gsdb:
    image: mysql
    container_name: 'gsdb'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  gsdbtest:
    image: mysql
    container_name: 'gsdbtest'
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - my-testdb:/var/lib/mysql
volumes:
  my-db:
  my-testdb: